softdevteam/snare

- snare
Without this, we ran into exception when we tried to read this header. Since we don't want to let people not specify secrets, failing is the right thing to do.
> If the X-Hub-Signature header isn't present, fail the secrets check.

- README.md
- snare
It seems likely that nearly all per-repo programs will want to write something to disk (at the very least cloning a repository), so running them in a temporary directory (which is automatically cleaned up after the program exits) makes the programs a little less error prone and a little easier to write.
> Always run per-repo programs in a temporary directory.

- Cargo.toml
- src/config.rs
- src/httpserver.rs
If someone manages to break into snare, this raises the bar for them to access the GitHub secret.
> Use SecStr to make it a bit harder to access the GitHub secret.

- Cargo.toml
- README.md
- build.rs
- src/config.l
- src/config.rs
- src/config.y
- src/httpserver.rs
- src/main.rs
At the moment, the amount of command-line switches we have is just about bearable, but this is likely to change profoundly in the future. This commit thus moves to a model of a simple configuration file.
@vext01 A question for you. My plan is for the next PR to move to a config format where you can start specifying this:
```
github {
match "*" {
timeout = 60
secret = "..."
}
match "user/repor" {
timeout = 600
}
}
```
i.e. something like PF where user can specify different settings per-repo, and that happens by matching the config file from top to bottom with "last matching setting wins".
Given the curly brackets (which seem the best way of specifying this config), would it be more idiomatic to have statements end with a semi-colon `;`? I can't quite make up my mind.
> Move to using a configuration file.

- Cargo.toml
- src/config.l
- src/config.rs
- src/httpserver.rs
- src/jobrunner.rs
- src/main.rs
- src/queue.rs
This PR enables snare to reload its config on SIGHUP. This is a bit more involved than it first seems because snare is multi-threaded. This PR thus goes through several stages (putting `Config` behind a `Mutex` and so on), before actually handling SIGHUP. Note that one case is handled somewhat, but not perfectly: reducing the value of `maxjobs`. I could do more here, but I think this is a niche case, and it's hard to test: the basic approach in this PR seems decent enough to me for the time being.
> Reload config after sighup

- README.md
- src/config.l
- src/config.rs
- src/config.y
- src/config_ast.rs
- src/jobrunner.rs
- src/queue.rs
This PR adds queue kinds: `queue = <evict|parallel|sequential>`. Previously `parallel` was all we supported, which had some comic outcomes: for example, for yksom, you could get race conditions trying to force push the `gh-pages` branch. `sequential` is now the default. Hopefully the README explains why these exist and why they might be useful.
This is the last major feature I think we need before a 0.1 release (though there are a few minor bits that probably need doing).
> Queue kinds

- README.md
- src/main.rs
It makes more sense to search for the per-user .snare.conf first before falling back to trying the global /etc/snare.conf.
> Change the order that we search for snare.conf.

- README.md
- src/config.rs
- src/main.rs
This requires a bit of reshuffling of the main method, as something in the `[tokio::main]` setup doesn't work with `daemon` (perhaps it creates threads, as `fork` only carries the main thread over to the child process).
> Daemonise by default (unless -d is passed on the command line).

- README.md
- src/config.l
- src/config.y
Although this is pure syntactic overhead for now, it will allow us one easy way of of unsetting options (e.g. `email=;`) should we ever want that in the future.
> Force "key=value" options to be terminated with a semi-colon.

- src/httpserver.rs
When a user installs a webhook, GitHub pings the webhook server. This simple commit responds with "success" if, and only if, authentication succeeds *and* there is a script for the repository in question.
@vext01 There is an interesting question here. Should we return success after authentication, even if there's not a script to run? To my mind, that equates to "things aren't fully set up yet, so best to make it clear", but I could be convinced otherwise.
> Respond to GitHub pings.

- README.md
- src/httpserver.rs
Previously we authenticated successfully if a signature was present, but if the GitHub side shared a secret, and our side didn't, we let it through anyway. In one sense this is fine, but it means that one can easily forget to specify a secret (and when I say "one", I mean "I have already made this mistake").
This commit thus returns `UNAUTHORIZED` if: the request is signed and we don't have a secret; we have a secret and the request isn't signed; or our secret doesn't match the signed request.
> Fail authentication if a secret is present.

- src/config.rs
- src/httpserver.rs
- src/jobrunner.rs
- src/main.rs
- src/queue.rs
In each case do one of the following:
* Ensure they are documented (and document if not) to explain why they're     safe.
* If they're not safe, make them safe (e.g. add a fallback, log an error).
The aim here is that snare should not fail at runtime due to `unwrap()` calls.
> Audit all the unwrap() calls.

- .buildbot.sh
- Cargo.toml
- deny.toml
This PR adds support for [cargo-deny](https://embarkstudios.github.io/cargo-deny/index.html), which makes it harder for us (or a dependency) to accidentally undermine the license we have chosen.
> Support for cargo-deny

- snare.1
- snare.conf.5
These mostly copy content over from `README.md`, adapting it for the `man` format, and with some minor changes. They pass through mandoc's `-T lint` successfully.
If/when this PR is merged, my plan would then be to make a further PR choping `README.md` down to the most essential details, and pointing people at HTML versions of the man pages held in a `gh-pages` branch.
> Add man pages for snare and snare.conf.

- Makefile
- README.md
In one sense the Makefile is unnecessary, but it means that normal Unix people who aren't familiar with Rust simply need to install Rust and then type "make install" in order for something sensible to happen. That feels like a reasonable compromise between old and new to me.
> Add install instructions and a basic Makefile.

- src/httpserver.rs
This PR tidies up a minor mistake from #39 (https://github.com/softdevteam/snare/commit/13b0b4af3c8583bea3c9a80517c3f681e3170b98), then validates the GitHub 'event' type (https://github.com/softdevteam/snare/commit/a9e1005e8ce731696d0b367cb8f57572fdd3441c) before explicitly logging why validation has failed (https://github.com/softdevteam/snare/commit/abdbe8268a46350fda60b9394a4df168af91e223).
> More input validation

- CHANGES.md
- README.md
- snare.conf.5
- src/config.l
- src/config.rs
- src/config.y
- src/config_ast.rs
- src/httpserver.rs
- src/jobrunner.rs
- src/main.rs
- src/queue.rs
This commit removes the `github`-block level `reposdir` and replaces it with the more flexible `match`-block level `cmd` has been introduced. In essence:
```
github {
reposdir = "/path/to/prps";
...
}
```
should be changed to:
```
github {
match ".*" {
cmd = "/path/to/reposdir/%o/%r %e %j";
}
}
```
in order to obtain the previous behaviour. `snare` informs users whose config contains `repodir` how to update it, hopefully minimising porting from snare-0.1.0.
> Replace GitHub-level 'reposdir' with match-level 'cmd'.

- .buildbot.sh
- CHANGES.md
- src/config.rs
Process escaped strings in the config file.
The regex in config.l supported strings such as:
```    
cmd = "\"\\";
```
but we didn't actually process the `\` characters, which was something of an oversight!
> String escapes

- src/config.l
- src/config.y
Consider this (incorrect) snippet of a snare.conf:
```
listen = "0.0.0.0:8011";
maxjob = 4;
```
Before this commit you would simply be told:
```
Lexing error at line 2 column 1.
```
which is accurate, but not very helpful. This commit adds a simple rule which, if no other lexing rules apply, consumes one character of the input into an "UNKNOWN" token. Thus every possible input can now be lexed, and lexing errors are now replaced by parsing errors, which means that error recovery can now kick in. Thus the above snippet now leads to:
```
Parsing error at line 2 column 1. Repair sequences found:
1: Insert MAXJOBS, Delete m, Delete a, Delete x, Delete j, Delete o, Delete b.
```
> Turn lexing errors into parsing errors.

- snare.conf.5
- src/main.rs
Previously we left snare with its CWD unchanged unless a `user` was specified at
which point we (for no obvious reason) changed CWD to `user`'s `$HOME`. This
small difference seems pointless: by always setting CWD to `/` we lessen the
chance of users relying on the CWD.
> Always chdir to '/'.

- README.md
- snare.conf.5
The previous version did not define the `$repo_url` variable. This version does, and also supports emailing multiple people (which is a small, but useful, extension).
> Fix and slightly extend the example email differ.

- CHANGES.md
- Cargo.lock
- Cargo.toml
- README.md
- build.rs
- snare.conf.5
- snare.conf.example
- src/config.l
- src/config.rs
- src/config.y
- src/config_ast.rs
- src/jobrunner.rs
The `email` option always felt a bit over-specific; this PR generalises `email` to `errorcmd` in the same way that 700ab030 generalised `reposdir` to `cmd`. `errorcmd` and `cmd` deliberately share almost identical syntax (the only difference being that `errorcmd` accepts an additional `%s` over `cmd`).
To obtain the previous behaviour:
```
email = "someone@example.com";
```
should be changed to:
```
errorcmd = "cat %s | mailx -s \"snare error: github.com/%o/%r\" someone@example.com";
```
> Deprecate the `email` option and replace it with `errorcmd`.

- README.md
I couldn't figure out why my script wasn't running and ended up putting
dbg!()s all over snare to find out why: Snare doesn't run the per-repo
program for ping messages. It just responds HTTP OK.
Let's inform users in README.md.
> Document what GitHub's test message does.

- README.md
- snare.conf.5
Before this, if GitHub went bad, they could possibly pass something that would cause `git log` to (at least) leak more information than we expected.
> Validate git commit hashes before passing them to `git log`.

- CHANGES.md
- Cargo.toml
The main reason for this release is to solve a slow memory leak in snare: each request would consume something around 24-32 bytes for no reason. I spent a while debugging this a couple of months ago, only to conclude that it didn't appear to be in the snare code itself but in a dependency (thought the waters were muddied by the fact that several dependencies allocated memory at various points, so it wasn't clear which might be the culprit).
Having now updated all the dependencies, I've run some stress tests (including firing a few tens of thousands of requests at snare), and the leak now appears to be gone. The first few requests cause snare's memory allocation to gradually increase but it soon stabilises (assuming, of course, that the queue doesn't grow: that's a perfectly good reason …
> Prepare a 0.4.1 release.

- .buildbot.sh
- Cargo.lock
- Cargo.toml
- src/main.rs
The last time I tried this, it failed, as some dependencies still relied on tokio < 1, and we ended up with two tokio runtimes being created, with the obvious outcome that nothing worked. It now seems that all the dependencies are
now working with tokio >= 1, so we can finally move forwards. I've also had to do "cargo update", so there's lots of obfuscating churn in `Cargo.lock`: the real changes are in `Cargo.toml`.
I've lightly tested this on b13 without issue and I'll keep it running on there for a while to see if anything crops up. However, I don't think there's a good reason not to consider merging this now.
> Move to tokio 1.

- snare.conf.5
If used, it now leads to a warning; it's not suitable for the man page.
> The reposdir option is long gone.

- Cargo.lock
- Cargo.toml
- src/httpserver.rs
- tests/basic.rs
This PR is overtly about fixing a problem in the new tests, which is that they used fixed port numbers (https://github.com/softdevteam/snare/commit/06a7e8ffc245e0621490f547ccaf28ef2619dc89). Fixing that made it obvious to me where the commonality in tests was, so this PR also cuts down a lot of the boilerplate.
> Don't bind to fixed ports in tests

- Makefile
This is based on recent changes to pizauth's Makefile. It respects `$DESTDIR` and also installs man pages in the correct (different!) location on both BSD and Linux. The downside is that the Makefile is now GNU make only.
> Use a Makefile that does a more portable installation.

- snare.conf.5
- src/config.rs
- src/jobrunner.rs
- tests/actions.rs
- tests/common/mod.rs
When `cmd` fails, the only clue as to why can be its exit code. Previously, snare had no way of transmitting this information to the user: this commit allows using `%x` and `%?` (the latter borrowing the similarly named variable from the shell) to in `errorcmd` to access this information.
> Allow `%x` and `%?` to be used in `errorcmd`.
